- hosts: supxen3.zenoss.loc
  remote_user: root

  tasks:

  - name: Prepare paths and files
    local_action: shell echo `whoami`
    register: username

  - name: Prepare paths and files part2
    local_action: shell cat /tmp/.supbuild-delete-{{ username.stdout }}
    register: uuid_to_delete
    
  - name: Powering off VM
    command: xe vm-shutdown --force  vm="{{ uuid_to_delete.stdout }}"
 
  - name: Deleting VM
    shell: xe vm-uninstall --force vm="{{ uuid_to_delete.stdout }}"
