- hosts: xenservers
  remote_user: root

  tasks:

  - name: Prepare paths and files
    local_action: shell echo `whoami`
    register: username

  - name: Prepare paths and files part2
    local_action: shell cat /tmp/.supbuild-poweron-{{ username.stdout }}
    register: uuid_to_poweron
    
  - name: Powering on VM
    command: xe vm-start vm="{{ uuid_to_poweron.stdout }}" ;echo ''
